name: Ofuscador Maestro y Despliegue Externo TV++

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar Repositorio Privado
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar Entorno de Servidor (Node 24)
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Instalar Herramientas de Cifrado
      run: npm install -g javascript-obfuscator

    - name: Clonar estructura de archivos
      run: |
        mkdir -p secure_build
        rsync -av --progress . secure_build --exclude .git --exclude .github --exclude secure_build

    - name: Blindar Todas las Listas Multimedia
      run: |
        shopt -s nullglob
        find secure_build -type f \( -name "*.m3u" -o -name "*.M3U" -o -name "*.json" -o -name "*.JSON" \) | while read f; do
          base64 -w 0 "$f" > "${f}.enc"
          rm "$f"
        done

    - name: Ofuscar Todos los Paneles Web y Scripts
      run: |
        shopt -s nullglob
        find secure_build -type f \( -name "*.html" -o -name "*.htm" \) | while read f; do
          javascript-obfuscator "$f" --output "$f" \
            --compact true \
            --self-defending false \
            --string-array true \
            --string-array-encoding 'base64' \
            --control-flow-flattening false || echo "Mitigación en $f"
        done

    - name: Desplegar en Repositorio Público Externo 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: secure_build
        repository-name: hackalka/player-publico # Lo mandamos a la fachada pública
        branch: main
        token: ${{ secrets.BOT_TOKEN_PUBLICO }} # Usará una llave que crearemos ahora
